/**
 * @wick-charts/svelte — Svelte bindings for Wick Charts.
 *
 * Everything importable from the library is re-exported here: components
 * (`<ChartContainer>`, `<CandlestickSeries>`, …), option types, and themes.
 * The underlying `@wick-charts/core` engine is bundled into this package —
 * its source lives at
 * https://github.com/mo4islona/wick-charts/tree/main/packages/core/src.
 */

export type {
  AnimationTime,
  AnimationsConfig,
  AxisBound,
  AxisConfig,
  BarElementTransform,
  BarEntryAnimation,
  BarIntroDirectives,
  BarIntroElement,
  BarIntroFn,
  BarIntroFrame,
  BarIntroValueArgs,
  BarPaintArgs,
  BarPainter,
  BarSeriesOptions,
  BaseSeriesRenderer,
  BitmapCoordinateSpace,
  BuildHoverSnapshotsArgs,
  BuildLastSnapshotsArgs,
  CandleElementTransform,
  CandleIntroDirectives,
  CandleIntroElement,
  CandleIntroFn,
  CandleIntroFrame,
  CandlePaintArgs,
  CandlePainter,
  CandlestickEntryAnimation,
  CandlestickSeriesOptions,
  ChartLayout,
  ChartOptions,
  ChartTheme,
  CornerMask,
  CrosshairPosition,
  CurveKind,
  CustomSpatialSeriesRenderer,
  EdgeReachedInfo,
  EdgeSide,
  EdgeState,
  HeatmapCellData,
  HeatmapCellLabelsOptions,
  HeatmapSeriesOptions,
  HeatmapSeriesRenderer,
  HoverInfo,
  LegendItem,
  LineIntroDirectives,
  LineIntroFn,
  LineIntroFrame,
  LineIntroValueArgs,
  LinePaintArgs,
  LinePainter,
  LineSeriesOptions,
  LoadingIndicatorArgs,
  LoadingIndicatorFn,
  MarkerConfig,
  MarkerShape,
  MultiLayerData,
  NavigatorCandlePoint,
  NavigatorControllerParams,
  NavigatorData,
  NavigatorLinePoint,
  NavigatorOptions,
  NavigatorSeriesType,
  OHLCData,
  OHLCInput,
  OverlayRenderContext,
  PaintEnv,
  PerfConfig,
  PerfMonitorOptions,
  PerfStats,
  PieSeriesOptions,
  PieSeriesRenderer,
  PieSliceData,
  PointClickInfo,
  ReferenceLineConfig,
  ReferenceLineOrientation,
  ReferenceLineStyle,
  RenderPadding,
  RoundedRectArgs,
  SeriesCreateEnv,
  SeriesDefinition,
  SeriesHoverInfo,
  SeriesKind,
  SeriesRenderContext,
  SeriesRenderer,
  SeriesSnapshot,
  SeriesType,
  SliceInfo,
  SnapshotSort,
  StackingMode,
  ThemeConfig,
  ThemePreset,
  TimeFormatOptions,
  TimeFormatter,
  TimePoint,
  TimePointInput,
  TimeRegionConfig,
  TimeRegionEnd,
  TimeSeriesRenderer,
  TimeTickGenerator,
  TimeValue,
  TooltipField,
  TooltipFormatter,
  TooltipPosition,
  TooltipPositionArgs,
  TracePathArgs,
  Transition,
  TransitionContext,
  TransitionFactory,
  Typography,
  ValueFormatter,
  ValueTickGenerator,
  VisibleRange,
  VisibleRangeSpec,
  WaveIntroDirectives,
  WaveIntroElement,
  WaveIntroFn,
  WaveIntroFrame,
  WaveIntroTransform,
  XAxisConfig,
  YAxisConfig,
  YRange,
} from '@wick-charts/core';
// Painters — custom per-element drawing for bar / candle / line series.
export {
  BarSeriesDef,
  CandlestickSeriesDef,
  ChartInstance,
  HeatmapSeriesDef,
  LineSeriesDef,
  NavigatorController,
  PerfMonitor,
  PieSeriesDef,
  XScale,
  YScale,
  andromeda,
  autoGradient,
  ayuMirage,
  backfillSweepIntro,
  buildHoverSnapshots,
  buildLastSnapshots,
  candleUnfoldIntro,
  catppuccin,
  centerOutIntro,
  computeTooltipPosition,
  createTheme,
  deepEqual,
  detectInterval,
  dracula,
  fadeIntro,
  fillRoundedRect,
  formatCompact,
  formatDate,
  formatPriceAdaptive,
  formatTime,
  githubLight,
  growIntro,
  gruvbox,
  handwritten,
  hermite,
  highContrast,
  isDarkBg,
  isTimeSeriesRenderer,
  lavenderMist,
  lightPink,
  materialPalenight,
  minimalLight,
  mintBreeze,
  mixColors,
  monokaiPro,
  nightOwl,
  normalizeTime,
  oneDarkPro,
  panda,
  parseAnimationTime,
  peachCream,
  perfHud,
  plotterIntro,
  quietLight,
  registerBuiltinSeries,
  registerSeriesDefinition,
  resolveAxisFontSize,
  resolveAxisTextColor,
  resolveCandlestickBodyColor,
  riseIntro,
  rosePineDawn,
  roundedBarFill,
  roundedCandleFill,
  sampleRamp,
  sandDune,
  skeletonLoadingIndicator,
  skeletonMorphIntro,
  smoothCurve,
  snap,
  solarizedLight,
  spring,
  springIntro,
  steppedCurve,
  straightCurve,
  sweepIntro,
  traceIntro,
  tracePath,
  unfoldIntro,
  wickBodyIntro,
  wipeIntro,
} from '@wick-charts/core';

export { default as BarSeries } from './BarSeries.svelte';
export { default as CandlestickSeries } from './CandlestickSeries.svelte';
// Svelte components
export { default as ChartContainer } from './ChartContainer.svelte';
// Context and stores
export { getChartContext, getThemeContext } from './context';
export { default as HeatmapSeries } from './HeatmapSeries.svelte';
export { default as LineSeries } from './LineSeries.svelte';
export { default as PieSeries } from './PieSeries.svelte';
export {
  createCrosshairPosition,
  createLastYValue,
  createPreviousClose,
  createVisibleRange,
  createYRange,
} from './stores';
export { default as Crosshair } from './ui/Crosshair.svelte';
export { default as HeatmapTooltip } from './ui/HeatmapTooltip.svelte';
export { default as InfoBar } from './ui/InfoBar.svelte';
export { default as Legend } from './ui/Legend.svelte';
export { default as Marker } from './ui/Marker.svelte';
export { default as Navigator } from './ui/Navigator.svelte';
export { default as NumberFlow } from './ui/NumberFlow.svelte';
export { default as PieLegend } from './ui/PieLegend.svelte';
export { default as PieTooltip } from './ui/PieTooltip.svelte';
export { default as ReferenceLine } from './ui/ReferenceLine.svelte';
export { default as TimeAxis, default as XAxis } from './ui/TimeAxis.svelte';
export { default as TimeRegion } from './ui/TimeRegion.svelte';
export { default as Title } from './ui/Title.svelte';
// UI overlays
export { default as Tooltip } from './ui/Tooltip.svelte';
export { default as YAxis } from './ui/YAxis.svelte';
export { default as YLabel } from './ui/YLabel.svelte';
