import {
  type ThemePreset,
  andromeda,
  ayuMirage,
  catppuccin,
  dracula,
  githubLight,
  gruvbox,
  handwritten,
  highContrast,
  lavenderMist,
  lightPink,
  materialPalenight,
  minimalLight,
  mintBreeze,
  monokaiPro,
  nightOwl,
  oneDarkPro,
  panda,
  peachCream,
  quietLight,
  rosePineDawn,
  sandDune,
  solarizedLight,
} from '@wick-charts/react';

export const themes: Record<string, ThemePreset> = {
  Dracula: dracula,
  'One Dark Pro': oneDarkPro,
  'Monokai Pro': monokaiPro,
  'Night Owl': nightOwl,
  'Material Palenight': materialPalenight,
  Gruvbox: gruvbox,
  Catppuccin: catppuccin,
  'Ayu Mirage': ayuMirage,
  Panda: panda,
  Andromeda: andromeda,
  Matrix: highContrast,
  Handwritten: handwritten,
  'GitHub Light': githubLight,
  'Solarized Light': solarizedLight,

  'Rosé Pine Dawn': rosePineDawn,
  'Quiet Light': quietLight,
  'Lavender Mist': lavenderMist,
  'Mint Breeze': mintBreeze,
  'Sand Dune': sandDune,

  'Peach Cream': peachCream,
  Monochrome: minimalLight,
  Love: lightPink,
};
